### ISSUE TITLE
Amplify stack contains Lambda function with outdated Node version

### ISSUE THREAD

**Issue by brecolic** [aws-samples/s3-object-lambda-workshop#2]
I am following the workshop instructions, and hitting the following error upon trying to deploy the Amplify CloudFormation stack:

`The following resources failed to deploy:
Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 5b67af15-e447-4733-b5d0-a11aa11ec749)" (RequestToken: 3ab9c037-aa6a-cdd7-e4bd-bc482d9dc46d, HandlerErrorCode: InvalidRequest)`

I can see that in `amplify/backend/auth/iamx1f8dd119/iamx1f8dd119-cloudformation-template.yml`, the `UserPoolClientLambda` resource is configured with a NodeJS runtime of: `nodejs12.x`. Since AWS no longer supports the creation of new Lambda functions with this runtime, I would recommend updating the CFN to a newer version of NodeJS.
<img width="816" alt="stack-failure" src="https://github.com/aws-samples/s3-object-lambda-workshop/assets/101430508/db9180ad-ba8d-4cfe-b44a-07e30f1f25cc">

**Comment by koiker** [comment]
Hi @brecolic,
I will check this error. Probably I will need to update some dependencies to make it work with the latest Node.js and modules.

**Comment by brecolic** [comment]
@koiker - I have a fix for this. I updated the runtime of `UserPoolClientLambda ` to `nodejs14.x` and re-ran the deployment, and was able to get the Amplify app successfully deployed and all other aspects of the workshop fully working. I initially tried the latest nodejs version of 18.x but this broke the deployment.
